### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by code-by** [christopherdro/react-native-html-to-pdf#47]
After updating React from 15.4 to 16.0.0, RN: 0.40.0 to 0.50.1, get error
```
:react-native-html-to-pdf:compileReleaseJavaWithJavac
.../app/node_modules/react-native-html-to-pdf/android/src/main/java/com/christopherdro/htmltopdf/RNHTMLtoPDFPackage.java:15: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: .../app/node_modules/react-native-html-to-pdf/android/src/main/java/com/christopherdro/htmltopdf/RNHTMLtoPDFModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-html-to-pdf:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

package.json:
```
    "react-native-html-to-pdf": "^0.4.0",
```
any solution?

**Comment by christopherdro** [comment]
Will update the library shortly

**Comment by sagarrs** [comment]
i am getting same error any solution ?
